### ISSUE TITLE
Sheets losing their custom fonts when you drag them

### ISSUE THREAD

**Issue by jgale** [kharrison/ScaledFont#3]
First, thanks for a brilliant package. This makes dealing with custom fonts in SwiftUI so nice. :)

I'm encountering a really weird bug. When I used `Text("string").scaledFont()` in a `.sheet()`, everything works fine once it's presented. All the custom scaled fonts are available. When I drag the sheet, the fonts lose all formatting. See this gif:

![disappearing_font](https://user-images.githubusercontent.com/942250/116127546-341b5600-a685-11eb-9109-0ec809d65273.gif)

The code for this is as simple as you'd expect. I'd share the whole package but can't share the fonts.

```swift
struct ContentView: View {
    @State private var sheetDisplayed = false

    var body: some View {
        Button("Show Sheet") {
            sheetDisplayed = true
        }
        .padding()
        .sheet(isPresented: $sheetDisplayed, content: {
            HowItWorks()
        })
    }
}

struct HowItWorks: View {
    @Environment(\.presentationMode) private var presentationMode

    var body: some View {
        VStack(spacing: 30) {
            Text("How it works")
                // This will not cause bug:
                // .scaledCustomFont(name: "GothamNarrSSm-Bold", size: 24)
                // This causes bug:
                .scaledFont(.headline)
                //.font(.largeTitle)
                .padding(.bottom, 30)

            Text("Last step")
                .scaledFont(.subheadline)
            Text("This is the last step. We will finish the process and then it's all done. Hooray!")
                .scaledFont(.callout)

            Button("Got it", action: { presentationMode.wrappedValue.dismiss() })
        }
        .padding()
    }
}
```

How ScaledFont is initialized:
```swift
@main
struct ScaledFontSheetBugApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
                .environment(\.scaledFont, ScaledFont(fontName: "Gotham"))
        }
    }
}
```

When I use the commented out `.scaledCustomFont` line, which is what I used before discovering your package, it works fine. Here's the definition of that:

```swift
struct ScaledCustomFont: ViewModifier {
    @Environment(\.sizeCategory) var sizeCategory
    var name: String
    var size: CGFloat

    func body(content: Content) -> some View {
       let scaledSize = UIFontMetrics.default.scaledValue(for: size)
        return content.font(.custom(name, size: scaledSize))
    }
}

extension View {
    func scaledCustomFont(name: String, size: CGFloat) -> some View {
        return modifier(ScaledCustomFont(name: name, size: size))
    }
}
```

Any idea what might be causing SwiftUI to lose all the fonts?

**Comment by kharrison** [comment]
That's interesting. I'll try and take a look

**Comment by kharrison** [comment]
I can reproduce the problem. I wonder if it's something to do with presented sheets being in their own view hierarchy? I remember that causing a problem in the past since they did not receive the environment from the presenting view. Though it's odd that it only seems to lose the font when dismissing.

**Comment by kharrison** [comment]
Here's a workaround that seems to suggest it is an environment issue. If I add the scaledFont object to the environment of the presented view it seems to work:

```swift
struct ContentView: View {
    @State private var sheetDisplayed = false
    @Environment(\.scaledFont) private var scaledFont

    var body: some View {
        Button("Show Sheet") {
            sheetDisplayed = true
        }
        .padding()
        .sheet(isPresented: $sheetDisplayed, content: {
            HowItWorks()
                .environment(\.scaledFont, scaledFont)
        })
    }
}
```

Not ideal, will have to investigate some more to see if there is a better way

**Comment by jgale** [comment]
Thanks very much for the workaround @kharrison. I will definitely use that for now.

I wouldn't be surprised if this is a SwiftUI bug. It feels similar to how you used to need to re-pass in `.environmentObject()` to any sheet that was created.

I just came across this [Reddit post](https://www.reddit.com/r/SwiftUI/comments/l6se15/environmentobject_sheet_woes/) which is describing the same behavior (though for `@EnvironmentObject`s, not `@Environment`). It would be nice to file a Feedback to Apple with a small reproducible example. I wish I knew what aspect of the `@Environment` is getting reset.

**Comment by kharrison** [comment]
My impression is that it's by design (at least for now). The presented sheet is its own view hierarchy so it doesn't inherit the usual environment of the presenting view. It's a bit of pain, so I wonder if we'll see it change in iOS 15.

For now, I'll add the workaround to the documentation as I'm sure it will catch me (and others) out again in the future.

Thanks for taking the time to report it.

**Comment by jgale** [comment]
The strange part is that it *does* get passed in to the sheet's view hierarchy automatically without you doing anything. It's just when you start to drag the sheet a bit that it gets reset somehow. It feels like a bug to me.

My pleasure, thanks again for the great package and write up.
